export const LOCATION_ONCHANGE = 'LOCATION_ONCHANGE';
export const PROXIMITY_ONCHANGE = 'PROXIMITY_ONCHANGE';
export const SET_MAP_CENTER = 'SET_MAP_CENTER';
export const HOTELS_SET = 'HOTELS_SET';
export const HOTELS_CLEAR = 'HOTELS_CLEAR';
